### ISSUE TITLE
Division by zero error while generating interaction periods for larger dataset

### ISSUE THREAD

**Issue by ps2** [WildflowerSchools/sensei#55]
```
878 obs from 2016-11-12T14:20:00.036962 to 2017-05-31T19:20:00.036930
Traceback (most recent call last):
  File "generate_interaction_periods.py", line 33, in <module>
    generate_interaction_periods(cid, most_recent.isoformat(), now.isoformat())
  File "/Users/pete/dev/sensei/app/analysis/interaction_periods.py", line 68, in generate_interaction_periods
    avg = idx_diff / (time_diff/TIME_DIFF_DENOMINATOR)
ZeroDivisionError: integer division or modulo by zero
```

**Comment by marknutter** [comment]
I think I have a fix for this in `b975b02459445a797e40155891a640be902a327c` if you want to try again, on the `activity-summary-viz`

**Comment by ps2** [comment]
That didn't fix it. TIME_DIFF_DENOMINATOR is an int, as is time_diff, so if time_diff is < 10, then we'll get a div by zero. I changed TIME_DIFF_DENOMINATOR to be 10.0, and that seems to work.

**Comment by marknutter** [comment]
Bah, good catch. Thanks!

Mark Nutter
